### ISSUE TITLE
[Feature 9] user-group id lookup

### ISSUE THREAD

**Issue by ileuxali** [CSC207-2022F-UofT/course-project-groupedup#6]
allows search function for user and group by their registered id

**Comment by ileuxali** [comment]
Completely finish Group/User ID lookup Use Case by November 10th. My first pull request will be done at latest by Nov 4th. The group will conduct code reviews between Nov 10th-14th. I will Integrate with my signup usecase to ensure IDs are created properly. ID lookup will search for a user or group with the inputted ID in our repository.

**Comment by aaryavatsa** [comment]
This feature is out of scope of the project. It is not included in the final presentation. This might be something to look at in the future.
