### ISSUE TITLE
[Feature 8] Edit pending list

### ISSUE THREAD

**Issue by SharonHsieh22** [CSC207-2022F-UofT/course-project-groupedup#8]
Allows group leaders to accept and reject users from their groups' pending lists.

**Comment by SharonHsieh22** [comment]
First pull request will be made by Nov. 4th.
Finish EditPendingList Use Case by Nov. 10th. 
Code reviews conducted Nov. 10th-Nov. 14th.
Will help implement the group and user classes so that they have all the instance atrributes and methods needed to implement my use case (e.g., edit group members list, edit user application list, etc.).
Will coordinate with Ipek, Aarya, and possibly Sohee and Julia to make sure the group and user entity interactions work.

**Comment by aaryavatsa** [comment]
This issue is closed -- great work Sharon!
